
[package]
name = "glsl-cookbook-rs"
version = "0.1.0"
authors = ["unknownue <usami-ssc@protonmail.com>"]
edition = "2018"
description = "A Rust implementation of *OpenGL 4 Shading Language Cookbook 3rd*"

[dependencies]
glium = "0.23.0"
