
[package]
name = "glsl-cookbook-rs"
version = "0.1.0"
authors = ["unknownue <usami-ssc@protonmail.com>"]
edition = "2018"
description = "A Rust implementation of *OpenGL 4 Shading Language Cookbook 3rd*"

[dependencies]
glium = "0.24.0"
vek = "0.9.7"
png = "0.15.0"
failure = "0.1.5"
lazy_static = "1.3.0"
